### PR TITLE
Create RANSOM_ryuk

### PR DESCRIPTION
**Pull request by morallo**
Rules for detecting ryuk ransomware, from NCSC advisory:
https://www.ncsc.gov.uk/news/ryuk-advisory

### CODE REVIEW

**Comment by morallo** [comment]
I requested permission to @NCSC since the rules are in a copyrighted document.

**Comment by jovimon** [comment]
Hey @morallo, have you got the permission to share the rules?

**Comment by morallo** [comment]
I wrote to them, but never got a reply 🙁

**Comment by Xumeiquer** [comment]
Any update on this? Otherwise the PR will be declined.

**Comment by morallo** [comment]
Unfortunately I never got a reply.

**Pull request closed without merging**
