### PR TITLE
Added FinSpy for Android rule.

### PR DESCRIPTION
**Pull request by devio**

### CODE REVIEW

**Comment by Xumeiquer** [comment]
Androguard rules are now deprecated so please move this rule to the deprecated folder.

**Comment by devio** [comment]
Could you please be a bit more verbose? I don't unsderstand what you would like to tell me.

**Comment by Xumeiquer** [comment]
Your FinSpy rule uses the android module which uses the Androguard plugin. Since Androguard seems to be a deprecated project we have decided to drop support for android based rules. Even that, you can still commit your rule, but instead of using the folder Mobile_malaware you must use the deprecated folder now.

**Comment by jovimon** [comment]
Done following the new folder structure in 1ca6ed3.

**Pull request closed without merging**
