### PR TITLE
Create RAT_CrossRAT.yar

### PR DESCRIPTION
**Pull request by simonsigre**
CrossRAT: a cross-platform implant, utilized in a global cyber-espionage campaign
https://objective-see.com/blog/blog_0x28.html
https://thehackernews.com/2018/01/crossrat-malware.html
https://malwaretips.com/threads/beware-undetectable-crossrat-malware-targets-windows-macos-and-linux-systems.79295/

### CODE REVIEW

**Comment by mmorenog** [comment]
Thank you Simon !

**Comment by r3d83ard** [comment]
Pretty new to the yara game, but this rule killed all matches for me. I think its the global designation on the private rule. Again brand new to yara, but just wanted to point this out if its an issue for others

**Comment by simonsigre** [comment]
Oh damn sorry, yeah it was one of my first. I tested this and it ran fine .. it does however search the entire machine .
Is what you mean by ‘killed’ that the CPU went through the roof?

**Comment by r3d83ard** [comment]
My bad, that was too broad. I mean I don't get matches on files that perviously did. In fact it stopped all matches on any file we analyzed. I think it is because global rules get applied before all other rules. "Global rules give you the possibility of imposing restrictions in all your rules at once." So the global has to be met then the other rules (all other rules?) get applied. No 100% on this, we've just started using it this month, so still learning. When I disable this rule, then the matches on other rules are back

**Comment by r3d83ard** [comment]
I think this is rule gets applied and the file has to meet these conditions first, then other rules are searched on
'''
global private rule javaarchive
 +{
 +    strings:
 +        $magic = { 50 4b 03 04 ( 14 | 0a ) 00 }
 +        $string_1 = "META-INF/"
 +        $string_2 = ".class" nocase
 +
 +	condition:
 +	    filesize < 400KB and
 +        $magic at 0 and 1 of ($string_*)
 +}
'''

**Comment by simonsigre** [comment]
Ahhh, so you are using this rule in with a bunch of others in the same file?
I set it up to be run by itself. I can fix this though. 
Can you show me the command you are running?

**Comment by r3d83ard** [comment]
Ah tracking. Yeah, we're running all the rules together at the moment, but will be pruning to what we need in the future.

`yara /rules/index.yar <file>`

**Comment by simonsigre** [comment]
Fair call.. ok yup, ill get this fixed up.. I have a few others to add soon also.
Need to get my head around some best practise with Yara, targeted location rules make me nervous as it seems to easy to pivot, so I am trying to do whole file system but use logic to skip over anything large before trying to hash.
I guess the other side to this is at what point does this project Yara-Rules just become a home-brew AV repo? I could semi-easily tie my work Sandboxes to a Yara rule creator.. but we would be submitted so many hashes every day.

**Comment by r3d83ard** [comment]
Yeah, I beginning to see this repo as more of a dumping ground, as oppose to a full rule set. Lots of dupes. Thanks for the rules!

**Pull request merged**
