### PR TITLE
Adding/modifying some rules

### PR DESCRIPTION
**Pull request by nyx0**

### CODE REVIEW

**Comment by yararules** [comment]
It's difficult to manage this pull request, by now. Shortly, we should have one file by malware family, then it will be more easy track changes.

**Comment by nyx0** [comment]
Ok my bad would you like that I modify my pull request to go in your way?

**Comment by yararules** [comment]
Can you split your PR? 

1. A PR to add rules
2. A PR to modify rules. Here it's important that you write why you modify the rule.
3. A PR to delete rules. Here it's important that you write why you delete the rule.

**Comment by nyx0** [comment]
@yararules ok I'll do it as soon as I can.

**Comment by jholgui** [comment]
Ok, thank you nyx0 :-)

**Pull request closed without merging**
