### PR TITLE
Red Leaves malware added

### PR DESCRIPTION
**Pull request by mutedmouse**
Courtesy of David Cannings and reddit release -12 hours.

### CODE REVIEW

**Comment by seifreed** [comment]
hey @mutedmouse thanks for the PR Can you give some hashes for the rule

"malware_red_leaves_memory"

Thanks!

**Comment by mutedmouse** [comment]
Checking in Virus total shortly to pull related hashes...will send and update rule when received.

**Comment by seifreed** [comment]
Sure!

Waiting the results!
--
Marc Rivero López | @seifreed | ecrime.pro

**Comment by seifreed** [comment]
Any update @mutedmouse ?

**Comment by seifreed** [comment]
added 

https://github.com/Yara-Rules/rules/commit/4aef9ec1946c38256d35b99073a5dd4630f3c1f6

**Pull request merged**
