### PR TITLE
Move more generic rules to Capabilities category.

### PR DESCRIPTION
**Pull request by knowmalware**

### CODE REVIEW

**Comment by Xumeiquer** [comment]
Please, review the travis error.

**Comment by Xumeiquer** [comment]
Folders were renamed, Can you please PR again?

**Comment by knowmalware** [comment]
You should still be able to apply this PR if you squash the commits.  I just tried on my local system and it worked fine.

If you're having trouble with that, just let me know and I'll cancel this PR and open a new one with the commits squashed.

**Comment by Xumeiquer** [comment]
Please, cancel the PR and do it again as it is having issues with androguard which is now deprecated from us.

**Pull request closed without merging**
